-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 15:17:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserTypes` (
  `idUserTypes` INT NOT NULL,
  `typeUserTypes` VARCHAR(45) NULL,
  PRIMARY KEY (`idUserTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `emailUsers` VARCHAR(45) NULL,
  `passwordUsers` VARCHAR(45) NULL,
  `typeUsers` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`),
  CONSTRAINT `idUserTypes`
    FOREIGN KEY ()
    REFERENCES `mydb`.`UserTypes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gyms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gyms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gyms` (
  `idGyms` INT NOT NULL,
  `nameGyms` VARCHAR(45) NULL,
  `addressGyms` VARCHAR(45) NULL,
  `telephoneGyms` VARCHAR(45) NULL,
  `emailGyms` VARCHAR(45) NULL,
  `ownerGyms` VARCHAR(45) NULL,
  PRIMARY KEY (`idGyms`),
  CONSTRAINT `idUsers`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipmentTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EquipmentTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentTypes` (
  `idEquipmentTypes` INT NOT NULL,
  `typeEquipmentTypes` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipmentTypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `idEquipment` INT NOT NULL,
  `locationEquipment` INT NULL,
  `typeEquipment` INT NULL,
  `currentStatusEquipment` TINYINT NULL,
  `updatedEquipment` DATETIME NULL,
  PRIMARY KEY (`idEquipment`),
  CONSTRAINT `idEquipmentTypes`
    FOREIGN KEY ()
    REFERENCES `mydb`.`EquipmentTypes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGyms`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Gyms` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reports` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reports` (
  `idReports` INT NOT NULL,
  `verifiedReports` TINYINT NOT NULL,
  `timestampReports` DATETIME NOT NULL,
  `authorReports` VARCHAR(45) NOT NULL,
  `equipmentReports` VARCHAR(45) NOT NULL,
  `descriptionReports` VARCHAR(255) NULL,
  PRIMARY KEY (`idReports`),
  CONSTRAINT `idUsers`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEquipment`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Equipment` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
