name: Zip and upload to S3

on:
  push:
    branches:
      - operations
  pull_request:
    branches:
      - operations

env:
  S3_BUCKET_NAME: gymchecks3
  AWS_REGION: us-east-1


jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install zip
        run: sudo apt-get install zip
      
      - name: Create zip file
        run: |
          export ZIP_NAME="$(git rev-parse --short HEAD)-$(date +%s).zip"
          zip -r $ZIP_NAME .
      
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
          with:
          aws_region: ${{env.AWS_REGSION}
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{env.S3_BUCKET_NAME}}
          source_dir: $ZIP_NAME