name: Zip and Push to S3

on:
  push:
    branches:
      - 'operations'
  pull_request:
    branches:
      - 'operations'

jobs:
  zip-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Zip the files
        run: zip -r gymcheck.zip .

      - name: Get random SHA name and assign to variable 
        id: vars
        run: echo ::set-output name=sha::$(openssl rand -hex 8)

      - name: Rename zip file
        run: mv gymcheck.zip gymcheck-${{ steps.vars.outputs.sha }}.zip

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: gymchecks3bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: gymcheck-${{ steps.vars.outputs.sha }}.zip
     