name: Zip and Push to S3

on:
  push:
    branches:
      - 'operations'
  pull_request:
    branches:
      - 'operations'

jobs:
  zip-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate SHA-1 hash
        id: hash
        run: |
          echo "::set-output name=hash::$(git rev-parse --short HEAD)-$(openssl rand -hex 4)"
      
      - name: Zip repository
        run: |
          zip -r ${{ steps.hash.outputs.hash }}.zip .
          echo "${{ steps.hash.outputs.hash }}".zip
      
