---
name: Deploy docker containers to ECS

env:
  MYSQL_USER: ${{ secrets.AWS_RDS_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
  MYSQL_HOST: ${{ secrets.AWS_RDS_HOST }}
  MYSQL_DATABASE: ${{ secrets.AWS_RDS_DBNAME }}

on:
  push:
    branches:
      - docker
  pull_request:
    branches:
      - docker

jobs:
  deploy-docker-containers-to-ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devopsgroup10projectdev
          IMAGE_TAG: 1
        run: |
          for service in $(docker-compose config --services); do
            echo "Building and pushing $service..."
            docker-compose build $service
            docker tag $service:latest 528775740130.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:latest
            docker push 528775740130.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:latest
          done
      



