name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - operations

env:
  AWS_REGION: us-east-1
  DOCKER_IMAGE_NAME: my-image
  DOCKERFILE_PATH: Dockerfile
  ECR_REPOSITORY_NAME: devopsgroup10projectdev
  ELASTIC_BEANSTALK_ENVIRONMENT_NAME: my-environment
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        id: build-image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$GITHUB_SHA -t $DOCKER_IMAGE_NAME:latest -f $DOCKERFILE_PATH .
          echo "::set-output name=image-uri::$DOCKER_IMAGE_NAME:$GITHUB_SHA"

      - name: Push Docker image to Amazon ECR
        id: push-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.build-image.outputs.image-uri }}
          registry: ${{ steps.login-ecr.outputs.registry }}

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          application_name: GymCheck
          environment_name: ${{ env.ELASTIC_BEANSTALK_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          command: "deploy"
          ignore_warnings: true