name: Zip and Push to S3

on:
  push:
    branches:
      - 'operations'
  pull_request:
    branches:
      - 'operations'

jobs:
  zip-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate SHA-1 hash
        id: hash
        run: |
          echo "::set-output name=hash::$(git rev-parse --short HEAD)-$(openssl rand -hex 4)"
      
      - name: Zip repository
        run: |
          cd $GITHUB_WORKSPACE
          zip -r $GITHUB_WORKSPACE/${{ steps.hash.outputs.hash }}.zip .
      
      - name: Push to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: gymchecks3bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: $GITHUB_WORKSPACE
          DEST_DIR: /
          EXCLUDE: "*.git*"
          S3_OBJECT_NAME: ${{ steps.hash.outputs.hash }}.zip 