---
name: Zip and upload to S3
on:
  push:
    branches:
      - operations
  pull_request:
    branches:
      - operations
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
  ZIP_FILE: 'filename'

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create zip file
        run: |
          export ZIP_NAME="$(git rev-parse --short HEAD)-$(date +%s).zip"
          zip -r $ZIP_NAME .
          echo "$ZIP_NAME"
          echo "$ZIP_NAME" >> ZIP_FILE

      - name: Echo Filename
        run: |
          echo "${{ ZIP_FILENAME }}"
          echo "${{ env.ZIP_FILENAME }}"

