---
name: Zip and upload to S3
on:
  push:
    branches:
      - operations
  pull_request:
    branches:
      - operations
env:
  s3_zip_name: $ZIP_NAME
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create zip file
        run: |
          export ZIP_NAME="$(git rev-parse --short HEAD)-$(date +%s).zip"
          zip -r $ZIP_NAME .

      - name: Show filename
        run: |
          echo "file name: ${{ env.s3_zip_name }}"
          echo "file name: $ZIP_NAME"
          

